import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function formatCurrency(amount: number) {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
  }).format(amount);
}

export function formatRating(rating: number) {
  return rating.toFixed(1);
}

export function getDifficultyColor(difficulty: string) {
  const colors: Record<string, string> = {
    Easy: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400",
    "Very Easy": "bg-teal-100 text-teal-700 dark:bg-teal-900/30 dark:text-teal-400",
    Medium: "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400",
    Hard: "bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400",
    Expert: "bg-rose-100 text-rose-700 dark:bg-rose-900/30 dark:text-rose-400",
    "Call Professional": "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400",
  };
  return colors[difficulty] || "bg-gray-100 text-gray-700 dark:bg-gray-900/30 dark:text-gray-400";
}

export function getWarningColor(level: string) {
  const colors: Record<string, string> = {
    Low: "bg-emerald-500",
    Medium: "bg-amber-500",
    High: "bg-orange-500",
    Critical: "bg-red-500",
  };
  return colors[level] || "bg-gray-500";
}

export function getUrgencyColor(urgency: string) {
  const colors: Record<string, string> = {
    Standard: "text-blue-600 bg-blue-50 dark:text-blue-400 dark:bg-blue-950/40",
    "Same Day": "text-amber-600 bg-amber-50 dark:text-amber-400 dark:bg-amber-950/40",
    Emergency: "text-red-600 bg-red-50 dark:text-red-400 dark:bg-red-950/40",
  };
  return colors[urgency] || "text-gray-600 bg-gray-50 dark:text-gray-400 dark:bg-gray-950/40";
}

export const servicesData = [
  {
    id: 1,
    title: "Replace Light Bulb",
    description: "Safe replacement of all types of light bulbs including LED, halogen, and fluorescent.",
    duration: "15 min",
    price: 50000,
    difficulty: "Very Easy",
    icon: "Lightbulb",
    category: "Basic",
  },
  {
    id: 2,
    title: "Replace Switch",
    description: "Replace faulty light switches with new, safe, and modern switches.",
    duration: "30 min",
    price: 85000,
    difficulty: "Easy",
    icon: "ToggleLeft",
    category: "Basic",
  },
  {
    id: 3,
    title: "Replace Socket",
    description: "Install new electrical outlets or replace damaged ones safely.",
    duration: "45 min",
    price: 120000,
    difficulty: "Easy",
    icon: "PlugZap",
    category: "Basic",
  },
  {
    id: 4,
    title: "Install Ceiling Lamp",
    description: "Professional ceiling lamp installation with proper wiring and support.",
    duration: "60 min",
    price: 180000,
    difficulty: "Medium",
    icon: "LampCeiling",
    category: "Installation",
  },
  {
    id: 5,
    title: "Install LED Strip",
    description: "Beautiful LED strip lighting installation with smart controls.",
    duration: "45 min",
    price: 150000,
    difficulty: "Easy",
    icon: "Ribbon",
    category: "Installation",
  },
  {
    id: 6,
    title: "Install Smart Switch",
    description: "Upgrade to smart switches compatible with Alexa, Google Home, Siri.",
    duration: "60 min",
    price: 220000,
    difficulty: "Medium",
    icon: "Smartphone",
    category: "Smart Home",
  },
  {
    id: 7,
    title: "Install Smart Doorbell",
    description: "Smart video doorbell installation with camera and app integration.",
    duration: "90 min",
    price: 280000,
    difficulty: "Medium",
    icon: "BellRing",
    category: "Smart Home",
  },
  {
    id: 8,
    title: "Install Ceiling Fan",
    description: "Ceiling fan installation with proper mounting and electrical connection.",
    duration: "90 min",
    price: 250000,
    difficulty: "Medium",
    icon: "Fan",
    category: "Installation",
  },
  {
    id: 9,
    title: "Install Exhaust Fan",
    description: "Bathroom and kitchen exhaust fan installation for ventilation.",
    duration: "75 min",
    price: 200000,
    difficulty: "Medium",
    icon: "Wind",
    category: "Installation",
  },
  {
    id: 10,
    title: "Repair Power Outage",
    description: "Diagnose and fix partial or complete electrical power failures.",
    duration: "120 min",
    price: 350000,
    difficulty: "Hard",
    icon: "ZapOff",
    category: "Repair",
  },
  {
    id: 11,
    title: "MCB Troubleshooting",
    description: "Diagnose Miniature Circuit Breaker issues and resolve tripping problems.",
    duration: "60 min",
    price: 200000,
    difficulty: "Hard",
    icon: "CircuitBoard",
    category: "Repair",
  },
  {
    id: 12,
    title: "Circuit Breaker Replacement",
    description: "Replace faulty circuit breakers with proper capacity units.",
    duration: "90 min",
    price: 300000,
    difficulty: "Hard",
    icon: "PanelLeft",
    category: "Repair",
  },
  {
    id: 13,
    title: "Electrical Inspection",
    description: "Comprehensive safety inspection of your home electrical system.",
    duration: "180 min",
    price: 450000,
    difficulty: "Expert",
    icon: "ClipboardCheck",
    category: "Maintenance",
  },
  {
    id: 14,
    title: "House Rewiring",
    description: "Complete or partial rewiring to modern electrical standards.",
    duration: "1-3 days",
    price: 5000000,
    difficulty: "Expert",
    icon: "Cable",
    category: "Major",
  },
  {
    id: 15,
    title: "Grounding Installation",
    description: "Proper electrical grounding system for home safety.",
    duration: "240 min",
    price: 850000,
    difficulty: "Expert",
    icon: "ShieldCheck",
    category: "Safety",
  },
  {
    id: 16,
    title: "EV Charger Installation",
    description: "Electric vehicle charging station installation at home.",
    duration: "180 min",
    price: 1500000,
    difficulty: "Expert",
    icon: "CarBattery",
    category: "EV",
  },
  {
    id: 17,
    title: "Solar Panel Consultation",
    description: "Expert assessment and planning for residential solar installation.",
    duration: "120 min",
    price: 350000,
    difficulty: "Expert",
    icon: "Sun",
    category: "Green Energy",
  },
  {
    id: 18,
    title: "Generator Installation",
    description: "Backup generator installation with automatic transfer switch.",
    duration: "480 min",
    price: 3500000,
    difficulty: "Expert",
    icon: "BatteryFull",
    category: "Major",
  },
];

export const diyGuides = [
  {
    id: 1,
    title: "Reset MCB (Circuit Breaker)",
    difficulty: "Very Easy",
    time: "5 min",
    tools: ["None required"],
    warning: "Low",
    safe: true,
    steps: [
      "Identify which MCB has tripped (it will be in the middle or OFF position)",
      "Push the lever fully to the OFF position",
      "Push it firmly back to the ON position",
      "If it trips again immediately, unplug devices on that circuit and try again",
      "If it keeps tripping, call a technician",
    ],
    icon: "CircuitBoard",
  },
  {
    id: 2,
    title: "Replace LED Bulb",
    difficulty: "Very Easy",
    time: "5 min",
    tools: ["Step ladder (if needed)"],
    warning: "Low",
    safe: true,
    steps: [
      "Turn OFF the light switch and wait 2 minutes for the old bulb to cool",
      "Gently twist the old bulb counterclockwise to remove it",
      "Check the wattage rating on the new LED bulb matches the fixture",
      "Insert the new LED bulb and twist clockwise until snug",
      "Turn the switch ON to test",
    ],
    icon: "Lightbulb",
  },
  {
    id: 3,
    title: "Test Outlet with Tester",
    difficulty: "Easy",
    time: "3 min",
    tools: ["Outlet tester / Multimeter"],
    warning: "Medium",
    safe: true,
    steps: [
      "Ensure your tester is calibrated and in good condition",
      "Hold the tester by the insulated handle only",
      "Insert tester prongs fully into the outlet slots",
      "Read the indicator lights: 2 yellow lights = correct wiring",
      "Any other pattern indicates wiring issues - call a technician",
    ],
    icon: "PlugZap",
  },
  {
    id: 4,
    title: "Use Voltage Tester Safely",
    difficulty: "Easy",
    time: "2 min",
    tools: ["Non-contact voltage tester"],
    warning: "Medium",
    safe: true,
    steps: [
      "Turn on the voltage tester and test on a known live outlet first",
      "Hold the tester tip against the wire or outlet slot",
      "A beep or light indicates voltage is present",
      "Always test both sides of a switch before touching wires",
      "Never assume power is off - always test first",
    ],
    icon: "Activity",
  },
  {
    id: 5,
    title: "Replace Extension Plug",
    difficulty: "Easy",
    time: "10 min",
    tools: ["Screwdriver", "Wire strippers"],
    warning: "Medium",
    safe: true,
    steps: [
      "UNPLUG the extension cord completely",
      "Unscrew the old plug and remove the cover",
      "Loosen the terminal screws and remove wires",
      "Strip 1cm insulation from each wire end",
      "Connect wires correctly: Live=Brown, Neutral=Blue, Earth=Green/Yellow",
      "Tighten screws, close the plug, and test with a continuity tester",
    ],
    icon: "Cable",
  },
  {
    id: 6,
    title: "Turn Off Main Breaker",
    difficulty: "Very Easy",
    time: "1 min",
    tools: ["None required"],
    warning: "Low",
    safe: true,
    steps: [
      "Locate your main electrical panel (usually near the meter)",
      "Stand to the side - never directly in front of the panel",
      "Find the largest breaker labeled 'MAIN'",
      "Push the lever firmly to the OFF position",
      "Test with a voltage tester to confirm power is off before any work",
    ],
    icon: "Power",
  },
  {
    id: 7,
    title: "Understand Electrical Symbols",
    difficulty: "Easy",
    time: "15 min",
    tools: ["Reference chart"],
    warning: "Low",
    safe: true,
    steps: [
      "Learn common symbols: ⚡ Light, 🔌 Outlet, ⊥ Ground, ⌁ Fuse",
      "Identify wire colors: Brown=Live, Blue=Neutral, Green/Yellow=Earth",
      "Understand your panel diagram - which breaker controls which area",
      "Label breakers clearly for future reference",
      "Keep a copy of the wiring diagram near the panel",
    ],
    icon: "BookOpen",
  },
  {
    id: 8,
    title: "When NOT to Repair Yourself",
    difficulty: "Call Professional",
    time: "N/A",
    tools: ["Just Call Us"],
    warning: "Critical",
    safe: false,
    steps: [
      "If you smell burning plastic - EVACUATE and call emergency",
      "If you see sparks or flames - Call 24/7 emergency service",
      "If you received an electric shock - Seek medical help first",
      "If wires are exposed or damaged in walls - Do not touch",
      "If there is water near wiring - Stay away completely",
      "If the breaker keeps tripping after reset - Call technician",
    ],
    icon: "AlertTriangle",
  },
];

export const whenToCallTech = [
  {
    id: 1,
    issue: "Burning Smell",
    danger: "Critical",
    action: "Evacuate immediately and call emergency service",
    urgency: "Emergency",
    description: "A burning plastic smell indicates wires are melting - fire hazard",
    icon: "Flame",
  },
  {
    id: 2,
    issue: "Sparks",
    danger: "Critical",
    action: "Turn off power and call emergency",
    urgency: "Emergency",
    description: "Visible sparks from outlets or switches indicate immediate danger",
    icon: "Zap",
  },
  {
    id: 3,
    issue: "Hot Outlet",
    danger: "High",
    action: "Unplug devices and book technician",
    urgency: "Same Day",
    description: "Warm outlets indicate loose wiring or overloaded circuit",
    icon: "FlameKindling",
  },
  {
    id: 4,
    issue: "Repeated Breaker Trip",
    danger: "High",
    action: "Do not keep resetting - book technician",
    urgency: "Same Day",
    description: "Breakers that keep tripping are trying to prevent a fire",
    icon: "AlertOctagon",
  },
  {
    id: 5,
    issue: "Electric Shock",
    danger: "Critical",
    action: "Seek medical attention then call technician",
    urgency: "Emergency",
    description: "Any shock from switches or appliances needs investigation",
    icon: "ZapOff",
  },
  {
    id: 6,
    issue: "Water Near Wiring",
    danger: "Critical",
    action: "Evacuate and turn off main breaker",
    urgency: "Emergency",
    description: "Water and electricity are deadly - do not approach",
    icon: "Droplets",
  },
  {
    id: 7,
    issue: "Burned Cable",
    danger: "High",
    action: "Do not touch - call technician immediately",
    urgency: "Same Day",
    description: "Discolored or burned wiring needs replacement urgently",
    icon: "Cable",
  },
  {
    id: 8,
    issue: "Buzzing Sound",
    danger: "Medium",
    action: "Investigate source and book technician",
    urgency: "Standard",
    description: "Faint buzzing may indicate loose connections or faulty fixtures",
    icon: "Volume2",
  },
  {
    id: 9,
    issue: "High Voltage Issue",
    danger: "Critical",
    action: "Turn off main power and call PLN first",
    urgency: "Emergency",
    description: "Overvoltage can destroy all connected appliances",
    icon: "TrendingUp",
  },
  {
    id: 10,
    issue: "Hidden Wiring Damage",
    danger: "High",
    action: "Book inspection service",
    urgency: "Standard",
    description: "Suspected rodent damage or age-related deterioration in walls",
    icon: "Bug",
  },
  {
    id: 11,
    issue: "Old Installation (20+ yrs)",
    danger: "Medium",
    action: "Schedule full inspection and consider rewiring",
    urgency: "Standard",
    description: "Old wiring may not meet modern safety standards",
    icon: "CalendarClock",
  },
  {
    id: 12,
    issue: "Flickering Lights",
    danger: "Medium",
    action: "If persistent across multiple fixtures, book technician",
    urgency: "Standard",
    description: "Could be loose wiring at the panel level",
    icon: "Lightbulb",
  },
];

export const electricians = [
  {
    id: 1,
    name: "Budi Santoso",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=faces",
    rating: 4.9,
    reviews: 342,
    completed: 1247,
    experience: "12 years",
    certificates: ["PLN Certified", "Master Electrician"],
    skills: ["Rewiring", "MCB Expert", "EV Chargers"],
    responseTime: "< 5 min",
    distance: "1.2 km",
    languages: ["ID", "EN"],
    verified: true,
    priceHour: 150000,
  },
  {
    id: 2,
    name: "Agus Wijaya",
    photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=faces",
    rating: 4.8,
    reviews: 218,
    completed: 892,
    experience: "8 years",
    certificates: ["PLN Certified"],
    skills: ["Smart Home", "Installation", "Solar"],
    responseTime: "< 8 min",
    distance: "2.5 km",
    languages: ["ID"],
    verified: true,
    priceHour: 125000,
  },
  {
    id: 3,
    name: "Siti Rahayu",
    photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=faces",
    rating: 5.0,
    reviews: 156,
    completed: 603,
    experience: "6 years",
    certificates: ["PLN Certified", "Safety Officer"],
    skills: ["Inspection", "Safety", "Consultation"],
    responseTime: "< 3 min",
    distance: "3.8 km",
    languages: ["ID", "EN", "ZH"],
    verified: true,
    priceHour: 140000,
  },
  {
    id: 4,
    name: "Hendra Permana",
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=faces",
    rating: 4.7,
    reviews: 489,
    completed: 1856,
    experience: "15 years",
    certificates: ["Master Electrician", "Solar PV Certified"],
    skills: ["Rewiring", "Generators", "Solar Panels"],
    responseTime: "< 10 min",
    distance: "4.1 km",
    languages: ["ID"],
    verified: true,
    priceHour: 175000,
  },
  {
    id: 5,
    name: "Dimas Firmansyah",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=faces",
    rating: 4.9,
    reviews: 276,
    completed: 1021,
    experience: "10 years",
    certificates: ["PLN Certified", "EVIT Certified"],
    skills: ["EV Chargers", "Smart Home", "Ceiling Fans"],
    responseTime: "< 6 min",
    distance: "1.9 km",
    languages: ["ID", "EN"],
    verified: true,
    priceHour: 160000,
  },
  {
    id: 6,
    name: "Rina Kartika",
    photo: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=faces",
    rating: 4.8,
    reviews: 134,
    completed: 512,
    experience: "5 years",
    certificates: ["PLN Certified"],
    skills: ["Lighting Design", "LED Strips", "Safety"],
    responseTime: "< 7 min",
    distance: "2.8 km",
    languages: ["ID", "EN"],
    verified: true,
    priceHour: 130000,
  },
];

export const reviews = [
  {
    id: 1,
    name: "Andi Pratama",
    avatar: "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=200&h=200&fit=crop&crop=faces",
    rating: 5,
    job: "House Rewiring",
    verified: true,
    date: "2 weeks ago",
    comment: "Absolutely professional service! Budi came on time, explained everything clearly, and completed the rewiring ahead of schedule. The cleanup was immaculate. Highly recommended!",
    photos: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&h=200&fit=crop",
    ],
  },
  {
    id: 2,
    name: "Maya Sucipta",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=faces",
    rating: 5,
    job: "EV Charger Installation",
    verified: true,
    date: "1 week ago",
    comment: "Dimas was phenomenal. He installed our EV charger perfectly and even helped us understand how to optimize charging times. His knowledge of smart home integration was impressive.",
    photos: [
      "https://images.unsplash.com/photo-1593941707882-a5bac6621214?w=300&h=200&fit=crop",
    ],
  },
  {
    id: 3,
    name: "Joko Susilo",
    avatar: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=200&h=200&fit=crop&crop=faces",
    rating: 4,
    job: "Emergency Power Outage",
    verified: true,
    date: "3 days ago",
    comment: "Called at 11pm, arrived in 25 minutes. Found the issue within 15 minutes and had power restored. Saved our dinner party! Siti was incredibly calm and professional.",
    photos: [],
  },
  {
    id: 4,
    name: "Linda Angelia",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=faces",
    rating: 5,
    job: "Smart Home Installation",
    verified: true,
    date: "1 month ago",
    comment: "Agus converted our entire home to smart lighting and switches. The attention to detail was remarkable. Everything works flawlessly with Google Home.",
    photos: [
      "https://images.unsplash.com/photo-1558002038-1055907df827?w=300&h=200&fit=crop",
    ],
  },
  {
    id: 5,
    name: "Rizky Maulana",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop&crop=faces",
    rating: 5,
    job: "Ceiling Fan x 4",
    verified: true,
    date: "5 days ago",
    comment: "Hendra installed 4 ceiling fans in one afternoon. Very neat work, no mess, no fuss. The fans are perfectly balanced and whisper quiet. Great value.",
    photos: [],
  },
];

export const blogPosts = [
  {
    id: 1,
    title: "Why Do Circuit Breakers Keep Tripping? 7 Common Causes",
    excerpt: "Understand the top reasons your breakers trip and when it's time to call a professional instead of just resetting.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop",
    category: "Safety",
    readTime: "6 min",
    date: "July 18, 2026",
    author: "Budi Santoso",
  },
  {
    id: 2,
    title: "10 Electrical Myths That Could Burn Your House Down",
    excerpt: "Don't fall for these dangerous misconceptions about home electricity. Myth vs. fact from certified master electricians.",
    image: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=600&h=400&fit=crop",
    category: "Myths",
    readTime: "8 min",
    date: "July 12, 2026",
    author: "Siti Rahayu",
  },
  {
    id: 3,
    title: "17 Proven Ways to Slash Your Electricity Bill This Month",
    excerpt: "From phantom loads to smart scheduling - real techniques used by energy experts to cut bills by 30-50%.",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&h=400&fit=crop",
    category: "Energy Saving",
    readTime: "10 min",
    date: "July 5, 2026",
    author: "Rina Kartika",
  },
  {
    id: 4,
    title: "Complete Beginner's Guide to Smart Home Electricals",
    excerpt: "Everything you need to know about smart switches, voice control, and home automation - without the confusion.",
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?w=600&h=400&fit=crop",
    category: "Smart Home",
    readTime: "12 min",
    date: "June 28, 2026",
    author: "Agus Wijaya",
  },
  {
    id: 5,
    title: "How to Hire a Trusted Electrician: Red Flags vs. Green Flags",
    excerpt: "A checklist of 20+ points to verify before letting anyone touch your home electrical system.",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop",
    category: "Guides",
    readTime: "7 min",
    date: "June 20, 2026",
    author: "Dimas Firmansyah",
  },
];

export const beforeAfterGallery = [
  {
    id: 1,
    title: "Old Panel Rewiring",
    before: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&h=400&fit=crop",
    after: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop",
    description: "Full consumer unit upgrade from old fuses to modern RCBO breakers",
  },
  {
    id: 2,
    title: "Kitchen Lighting Upgrade",
    before: "https://images.unsplash.com/photo-1556912167-f556f1f39fbb?w=600&h=400&fit=crop",
    after: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=400&fit=crop",
    description: "Single fluorescent replaced with premium LED downlight array",
  },
  {
    id: 3,
    title: "Exposed Wires to Smart Outlets",
    before: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=600&h=400&fit=crop",
    after: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&h=400&fit=crop",
    description: "Dangerous open wiring replaced with grounded smart USB outlets",
  },
  {
    id: 4,
    title: "Outdoor Lighting Install",
    before: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop",
    after: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&h=400&fit=crop",
    description: "Garden path and facade lighting with motion sensors",
  },
];

export const safetyTopics = [
  {
    id: 1,
    title: "Electrical Safety Basics",
    icon: "ShieldAlert",
    color: "from-blue-500 to-cyan-500",
    points: ["Never touch outlets with wet hands", "Unplug appliances before cleaning", "Keep cords away from heat sources", "Use GFCI in bathrooms & kitchen"],
  },
  {
    id: 2,
    title: "Child Protection",
    icon: "Baby",
    color: "from-pink-500 to-rose-500",
    points: ["Install socket covers on all outlets", "Keep cords out of reach", "Teach children not to insert objects", "Consider tamper-resistant outlets"],
  },
  {
    id: 3,
    title: "Fire Prevention",
    icon: "Flame",
    color: "from-orange-500 to-red-500",
    points: ["Don't daisy-chain power strips", "Replace damaged cords immediately", "Keep flammables away from panels", "Test smoke alarms monthly"],
  },
  {
    id: 4,
    title: "Safe Extension Cords",
    icon: "Cable",
    color: "from-amber-500 to-orange-500",
    points: ["Use correct gauge for load", "Never run under rugs", "Don't overload one outlet", "Inspect for damage before use"],
  },
  {
    id: 5,
    title: "Energy Saving Tips",
    icon: "Leaf",
    color: "from-emerald-500 to-green-500",
    points: ["Switch to LED lighting", "Use smart power strips", "Install programmable thermostat", "Unplug phantom load devices"],
  },
  {
    id: 6,
    title: "Lightning Protection",
    icon: "CloudLightning",
    color: "from-violet-500 to-purple-500",
    points: ["Install whole-home surge protector", "Unplug during storms", "Ground outdoor antennas", "Consider lightning rods for tall buildings"],
  },
  {
    id: 7,
    title: "Understanding MCB",
    icon: "CircuitBoard",
    color: "from-sky-500 to-blue-500",
    points: ["MCB protects against overload", "RCD/RCBO protects against shock", "Know which breaker controls what", "Test RCD button monthly"],
  },
  {
    id: 8,
    title: "Grounding Explained",
    icon: "ArrowDownToLine",
    color: "from-teal-500 to-emerald-500",
    points: ["Grounding prevents electrocution", "3-prong plugs must have ground", "Never remove the ground pin", "Test outlets for proper grounding"],
  },
  {
    id: 9,
    title: "Monthly Inspection Checklist",
    icon: "CheckSquare",
    color: "from-indigo-500 to-blue-500",
    points: ["Check all outlets for warmth", "Listen for buzzing sounds", "Test RCD/ELCB buttons", "Inspect visible cords for damage"],
  },
];

export const faqs = [
  {
    q: "How quickly can a technician arrive?",
    a: "Standard bookings arrive within 2-4 hours of your scheduled window. Emergency service has an average response time of 30-45 minutes within city limits, 24/7 including holidays.",
  },
  {
    q: "Are your electricians licensed and insured?",
    a: "Yes! Every VoltCare electrician is PLN certified, has a valid Ministry of Manpower electrical work license (SIO), is fully insured with professional liability coverage, and has passed our rigorous 15-point vetting process including background check and skills assessment.",
  },
  {
    q: "What if I'm not satisfied with the work?",
    a: "We offer a 90-day workmanship guarantee on all services. If you experience any issue related to our work within 90 days, we'll send a technician back for free. If you're still unsatisfied, we offer a 100% money-back guarantee.",
  },
  {
    q: "How is pricing determined? Are there hidden fees?",
    a: "All pricing is transparent and shown upfront before you confirm the booking. You pay the exact price shown - no hidden fees, no surprises. The final invoice includes: service fee, parts used (with itemized receipt), travel fee (if applicable), and any night/weekend surcharges clearly disclosed at booking.",
  },
  {
    q: "Do I need to provide any parts or tools?",
    a: "No. Our electricians arrive fully equipped with all necessary tools and a wide range of standard spare parts. Specialty parts (smart switches, specific fixtures, EV chargers) can be supplied by you or purchased through VoltCare at cost + 10% handling fee - you always get to choose.",
  },
  {
    q: "Can I get a quote before confirming?",
    a: "Absolutely. For standard services, prices are fixed and shown instantly. For complex jobs (rewiring, generator install, solar), we offer a paid inspection first (Rp 150,000, deductible from final invoice) where a technician assesses your property and provides a detailed written quote within 24 hours.",
  },
  {
    q: "What payment methods do you accept?",
    a: "We accept: all major credit cards (Visa, Mastercard, Amex, JCB), bank transfer (BCA, Mandiri, BNI, BRI), e-wallets (GoPay, OVO, DANA, ShopeePay), cash on completion (with receipt), and installment plans via Traveloka PayLater and Kredivo for orders above Rp 1,000,000.",
  },
  {
    q: "Do you service apartments/complexes with strict rules?",
    a: "Yes. We regularly work in apartments and gated communities. If management requires paperwork or vendor registration, we handle it for you. We recommend booking 24 hours in advance for apartments so we can coordinate access with your building management office.",
  },
  {
    q: "What about warranty on parts installed?",
    a: "Parts installed by VoltCare carry their full manufacturer warranty. For most parts this is 1-2 years; smart home devices often carry 2-5 year warranties. We keep all receipts on file and help you process warranty claims at no extra charge.",
  },
  {
    q: "Can I request a specific technician?",
    a: "Yes! If you've had a great experience with someone, you can favorite them in your account and request them for future jobs. You can also filter technicians by skills, rating, distance, and price before booking.",
  },
  {
    q: "What happens if the technician is late?",
    a: "We send live tracking 30 minutes before arrival with the technician's photo, vehicle, and contact info. If they arrive outside the scheduled window without prior notification, you automatically receive a 20% discount on the service fee as our apology.",
  },
  {
    q: "Do you offer commercial/office services?",
    a: "Yes. VoltCare Business serves offices, retail, restaurants, warehouses, and property managers with dedicated account managers, after-hours service, monthly retainers, and consolidated billing. Contact our business team for a custom proposal.",
  },
  {
    q: "How does the DIY section work?",
    a: "Our DIY Center has free, professionally-reviewed guides for safe, simple repairs. Each guide includes required tools, warnings, step-by-step instructions, and a clear 'STOP - call technician' message if the situation escalates. We never encourage unsafe work.",
  },
  {
    q: "Is my personal info safe?",
    a: "Absolutely. We are PDP (Personal Data Protection) compliant, use bank-level 256-bit SSL encryption on all pages, never sell your data to third parties, and offer two-factor authentication for account security.",
  },
  {
    q: "Can I cancel or reschedule?",
    a: "Free cancellation or reschedule up to 2 hours before the scheduled time. Cancellations within 2 hours incur a 30% no-show fee. Same-day emergency bookings can be rescheduled but not cancelled once the technician is dispatched.",
  },
  {
    q: "What safety protocols do technicians follow?",
    a: "All technicians follow OSHA-compliant procedures: wear appropriate PPE, use insulated tools, lockout/tagout circuits when working, place safety barriers, clean up the work area, and walk you through the completed work with photos before leaving.",
  },
  {
    q: "Do you install EV chargers? Can you help with permits?",
    a: "Yes, we are an officially certified installer for major EV brands (Tesla, BYD, Hyundai, Wuling, MG). We handle the entire process including assessing your electrical panel capacity, recommending the right charger, assisting with PLN application for additional capacity (if needed), installation, and final testing.",
  },
  {
    q: "What areas do you cover?",
    a: "Currently we serve: Greater Jakarta (Jabodetabek), Bandung, Surabaya, Semarang, Yogyakarta, Bali, Medan, and Makassar. New cities added monthly. Sign up for our newsletter to be notified when we launch in your area.",
  },
  {
    q: "How does the Smart Troubleshooter work?",
    a: "Our interactive diagnostic tool asks a series of targeted questions about your electrical issue. Based on your answers, our algorithm recommends: (1) a DIY fix with guide if safe, (2) book a standard technician, or (3) call emergency service immediately. This helps you get the right level of help and avoid unnecessary costs.",
  },
  {
    q: "Can I join VoltCare as an electrician?",
    a: "We're always hiring certified electricians! Apply through our 'Become a Technician' page. Requirements: valid SIO license, minimum 3 years experience, clean background check, own tools and transportation. Top techs on our platform earn Rp 15-30 million/month with flexible hours.",
  },
  {
    q: "Do you have a loyalty or referral program?",
    a: "Yes! VoltCare Rewards: earn 50 points per booking (1 point = Rp 100) plus bonus points for reviews. Refer a friend: you both get Rp 150,000 off your next booking. We also run seasonal promotions and send exclusive coupon codes to our app users.",
  },
];

export const pricingData = [
  {
    category: "Inspection",
    items: [
      { name: "Visual Safety Check", price: 100000, duration: "30 min", details: ["Outlet & switch inspection", "Panel visual check", "Basic report"] },
      { name: "Comprehensive Inspection", price: 450000, duration: "3 hrs", details: ["Full wiring assessment", "Load testing", "Thermal imaging (selected areas)", "PDF report with recommendations"] },
      { name: "Pre-Purchase House Check", price: 750000, duration: "5 hrs", details: ["Complete electrical audit", "Code compliance check", "Cost estimate for repairs", "Priority 48hr report"] },
    ],
  },
  {
    category: "Installation",
    items: [
      { name: "Light Fixture", price: 180000, duration: "1 hr", details: ["Standard ceiling/wall fixture", "Includes basic bracket", "Testing & cleanup"] },
      { name: "Ceiling Fan", price: 250000, duration: "1.5 hrs", details: ["Fan assembly included", "Bracing & support check", "Balance adjustment"] },
      { name: "Smart Switch (per unit)", price: 220000, duration: "1 hr", details: ["Neutral wire check", "WiFi setup included", "App walkthrough"] },
      { name: "EV Charger (Level 2)", price: 1500000, duration: "3-4 hrs", details: ["7-22kW charger", "Permit assistance", "WiFi/smart features setup"] },
    ],
  },
  {
    category: "Repair",
    items: [
      { name: "Outlet / Switch Replacement", price: 120000, duration: "45 min", details: ["Per unit", "Standard parts included", "Voltage testing"] },
      { name: "Breaker / MCB Replacement", price: 300000, duration: "1.5 hrs", details: ["Per breaker + diagnosis", "Suitable replacement unit", "Load verification"] },
      { name: "Power Outage Diagnosis", price: 350000, duration: "2 hrs", details: ["Troubleshooting up to 2hrs", "Partial fix where safe", "Quote for major work"] },
    ],
  },
  {
    category: "Emergency & Premium",
    items: [
      { name: "24/7 Emergency Callout", price: 500000, duration: "< 45 min", details: ["Immediate dispatch", "Night/holiday included", "Flat callout + work fee"] },
      { name: "Night Service (18:00 - 08:00)", price: "+ 50%", duration: "Std + 50%", details: ["After-hours premium", "Applies 6pm to 8am"] },
      { name: "Weekend / Holiday", price: "+ 30%", duration: "Std + 30%", details: ["Sat-Sun + national holidays"] },
      { name: "Travel Fee (beyond 5km)", price: 15000, duration: "per extra km", details: ["First 5km included", "Charged from nearest hub", "Capped at Rp 150,000"] },
    ],
  },
];
